version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  lint:
    docker:
      - image: cimg/node:17.3.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Lint monorepo
          command: yarn lint:monorepo
      - run:
          name: Lint
          command: yarn lint:eslint
      - run:
          name: Lint style
          command: yarn lint:style
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: Ensure changelong
          command: yarn version check
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff

  compile-and-test:
    docker:
      - image: cimg/node:17.3.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests
          command: yarn test -- --ci

  publish:
    docker:
      - image: cimg/node:17.3.1
    steps:
      - run:
          name: Publish all packages [dry run]
          command: yarn workspaces foreach --no-private --parallel --topological --verbose run prepublish
      - run:
          name: Publish all packages
          command: yarn workspaces foreach --no-private --parallel --topological --verbose npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - compile-and-test:
          filters:
            tags:
              only: /.*/
          requires:
            - lint

      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - compile-and-test
          context: npm
